/**
 * @fileoverview gRPC-Web generated client stub for user.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.19.1
// source: user.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.user = {};
proto.user.v1 = require('./user_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.user.v1.UserServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.user.v1.UserServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.user.v1.GetUserRequest,
 *   !proto.user.v1.GetUserResponse>}
 */
const methodDescriptor_UserService_GetUser = new grpc.web.MethodDescriptor(
  '/user.v1.UserService/GetUser',
  grpc.web.MethodType.UNARY,
  proto.user.v1.GetUserRequest,
  proto.user.v1.GetUserResponse,
  /**
   * @param {!proto.user.v1.GetUserRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.user.v1.GetUserResponse.deserializeBinary
);


/**
 * @param {!proto.user.v1.GetUserRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.user.v1.GetUserResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.user.v1.GetUserResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.user.v1.UserServiceClient.prototype.getUser =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/user.v1.UserService/GetUser',
      request,
      metadata || {},
      methodDescriptor_UserService_GetUser,
      callback);
};


/**
 * @param {!proto.user.v1.GetUserRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.user.v1.GetUserResponse>}
 *     Promise that resolves to the response
 */
proto.user.v1.UserServicePromiseClient.prototype.getUser =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/user.v1.UserService/GetUser',
      request,
      metadata || {},
      methodDescriptor_UserService_GetUser);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.user.v1.ListUsersRequest,
 *   !proto.user.v1.User>}
 */
const methodDescriptor_UserService_ListUsers = new grpc.web.MethodDescriptor(
  '/user.v1.UserService/ListUsers',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.user.v1.ListUsersRequest,
  proto.user.v1.User,
  /**
   * @param {!proto.user.v1.ListUsersRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.user.v1.User.deserializeBinary
);


/**
 * @param {!proto.user.v1.ListUsersRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.user.v1.User>}
 *     The XHR Node Readable Stream
 */
proto.user.v1.UserServiceClient.prototype.listUsers =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/user.v1.UserService/ListUsers',
      request,
      metadata || {},
      methodDescriptor_UserService_ListUsers);
};


/**
 * @param {!proto.user.v1.ListUsersRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.user.v1.User>}
 *     The XHR Node Readable Stream
 */
proto.user.v1.UserServicePromiseClient.prototype.listUsers =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/user.v1.UserService/ListUsers',
      request,
      metadata || {},
      methodDescriptor_UserService_ListUsers);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.user.v1.SubscribeChatRequest,
 *   !proto.user.v1.ChatMessage>}
 */
const methodDescriptor_UserService_SubscribeChat = new grpc.web.MethodDescriptor(
  '/user.v1.UserService/SubscribeChat',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.user.v1.SubscribeChatRequest,
  proto.user.v1.ChatMessage,
  /**
   * @param {!proto.user.v1.SubscribeChatRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.user.v1.ChatMessage.deserializeBinary
);


/**
 * @param {!proto.user.v1.SubscribeChatRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.user.v1.ChatMessage>}
 *     The XHR Node Readable Stream
 */
proto.user.v1.UserServiceClient.prototype.subscribeChat =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/user.v1.UserService/SubscribeChat',
      request,
      metadata || {},
      methodDescriptor_UserService_SubscribeChat);
};


/**
 * @param {!proto.user.v1.SubscribeChatRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.user.v1.ChatMessage>}
 *     The XHR Node Readable Stream
 */
proto.user.v1.UserServicePromiseClient.prototype.subscribeChat =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/user.v1.UserService/SubscribeChat',
      request,
      metadata || {},
      methodDescriptor_UserService_SubscribeChat);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.user.v1.ChatMessage,
 *   !proto.user.v1.SendChatMessageResponse>}
 */
const methodDescriptor_UserService_SendChatMessage = new grpc.web.MethodDescriptor(
  '/user.v1.UserService/SendChatMessage',
  grpc.web.MethodType.UNARY,
  proto.user.v1.ChatMessage,
  proto.user.v1.SendChatMessageResponse,
  /**
   * @param {!proto.user.v1.ChatMessage} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.user.v1.SendChatMessageResponse.deserializeBinary
);


/**
 * @param {!proto.user.v1.ChatMessage} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.user.v1.SendChatMessageResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.user.v1.SendChatMessageResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.user.v1.UserServiceClient.prototype.sendChatMessage =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/user.v1.UserService/SendChatMessage',
      request,
      metadata || {},
      methodDescriptor_UserService_SendChatMessage,
      callback);
};


/**
 * @param {!proto.user.v1.ChatMessage} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.user.v1.SendChatMessageResponse>}
 *     Promise that resolves to the response
 */
proto.user.v1.UserServicePromiseClient.prototype.sendChatMessage =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/user.v1.UserService/SendChatMessage',
      request,
      metadata || {},
      methodDescriptor_UserService_SendChatMessage);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.user.v1.LoginRequest,
 *   !proto.user.v1.LoginResponse>}
 */
const methodDescriptor_UserService_Login = new grpc.web.MethodDescriptor(
  '/user.v1.UserService/Login',
  grpc.web.MethodType.UNARY,
  proto.user.v1.LoginRequest,
  proto.user.v1.LoginResponse,
  /**
   * @param {!proto.user.v1.LoginRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.user.v1.LoginResponse.deserializeBinary
);


/**
 * @param {!proto.user.v1.LoginRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.user.v1.LoginResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.user.v1.LoginResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.user.v1.UserServiceClient.prototype.login =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/user.v1.UserService/Login',
      request,
      metadata || {},
      methodDescriptor_UserService_Login,
      callback);
};


/**
 * @param {!proto.user.v1.LoginRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.user.v1.LoginResponse>}
 *     Promise that resolves to the response
 */
proto.user.v1.UserServicePromiseClient.prototype.login =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/user.v1.UserService/Login',
      request,
      metadata || {},
      methodDescriptor_UserService_Login);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.user.v1.ServerInfoRequest,
 *   !proto.user.v1.ServerInfo>}
 */
const methodDescriptor_UserService_GetServerInfo = new grpc.web.MethodDescriptor(
  '/user.v1.UserService/GetServerInfo',
  grpc.web.MethodType.UNARY,
  proto.user.v1.ServerInfoRequest,
  proto.user.v1.ServerInfo,
  /**
   * @param {!proto.user.v1.ServerInfoRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.user.v1.ServerInfo.deserializeBinary
);


/**
 * @param {!proto.user.v1.ServerInfoRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.user.v1.ServerInfo)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.user.v1.ServerInfo>|undefined}
 *     The XHR Node Readable Stream
 */
proto.user.v1.UserServiceClient.prototype.getServerInfo =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/user.v1.UserService/GetServerInfo',
      request,
      metadata || {},
      methodDescriptor_UserService_GetServerInfo,
      callback);
};


/**
 * @param {!proto.user.v1.ServerInfoRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.user.v1.ServerInfo>}
 *     Promise that resolves to the response
 */
proto.user.v1.UserServicePromiseClient.prototype.getServerInfo =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/user.v1.UserService/GetServerInfo',
      request,
      metadata || {},
      methodDescriptor_UserService_GetServerInfo);
};


module.exports = proto.user.v1;

